package com.app.kerja_mudah.core.constant


// CHECK BEFORE DELETE
object ParamsKeySP {
    const val PARAMS_SP_KEY = "PARAMS_SP"


    const val CODE_LANGUAGE_APP = "CODE_LANGUAGE_APP"

    // AUTH REPOSITORY
    const val ACCESS_TOKEN = "ACCESS_TOKEN"
    const val MY_PROFILE = "MY_PROFILE"
    const val TOTAL_UNREAD_ORDER_SERVICE = "TOTAL_UNREAD_ORDER_SERVICE"

    // FREELANCER REPOSITORY
    const val REGISTER_FREELANCER_CATEGORY = "REGISTER_FREELANCER_CATEGORY"
    const val REGISTER_FREELANCER_NAME = "REGISTER_FREELANCER_NAME"
    const val REGISTER_FREELANCER_DESCRIPTION = "REGISTER_FREELANCER_DESCRIPTION"
    const val REGISTER_FREELANCER_HIGHLIGHT_PHOTO = "REGISTER_FREELANCER_HIGHLIGHT_PHOTO"
    const val REGISTER_FREELANCER_HIGHLIGHT_VIDEO = "REGISTER_FREELANCER_HIGHLIGHT_VIDEO"
    const val REGISTER_FREELANCER_ID_CARD = "REGISTER_FREELANCER_ID_CARD"
    const val REGISTER_FREELANCER_SELFIE_ID_CARD = "REGISTER_FREELANCER_SELFIE_ID_CARD"

    // QURAN REPOSITORY
    const val QURAN_FONT_SIZE = "QURAN_FONT_SIZE"

    // WEATHER REPOSITORY
    const val PROVINCE_SELECTED = "PROVINCE_SELECTED"
    const val CITY_SELECTED = "CITY_SELECTED"
    const val PROVINCE_RESPONSE = "PROVINCE_RESPONSE"
}